# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 소개
    url: /
    weight: 100
  - name: 작업
    url: 작업
    weight: 200
  - parent: 프로젝트
    name: 공부
    url: /#study
    weight: 210
  - parent: 작업
    name: 프로젝트
    url: /#project
    weight: 220
  - name: 정보
    url: 정보
    weight: 300
  - parent: 정보
    name: 취미
    url: /#hobby
    weight: 310
  - parent: 정보
    name: 경험
    url: experience/
    weight: 320
  - name: 소식
    url: /#news
    weight: 410
