# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 100
  - name: Project
    url: 프로젝트
    weight: 200
  - parent: Project
    name: Study
    url: study/
    weight: 210
  - parent: Project
    name: project
    url: project/
    weight: 220
  - name: hobby
    url: hobby/
    weight: 300
  - name: experience
    url: experience/
    weight: 400
  - name: news
    url: /#news
    weight: 500
