# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 소개
    url: /
    weight: 100
  - name: 프로젝트
    url: 프로젝트
    weight: 200
  - parent: 프로젝트
    name: 공부
    url: study/
    weight: 210
  - parent: 프로젝트
    name: 작업물
    url: project/
    weight: 220
  - name: 취미
    url: hobby/
    weight: 300
  - name: 경험
    url: experience/
    weight: 400
  - name: 소식
    url: /#news
    weight: 500
